# NumPy Array Basics - Multi-dimensional Arrays

In [1]:
import sys
import numpy as np
print sys.version

2.7.11 |Anaconda 2.2.0 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)]


In [2]:
npa = np.arange(25)

In [3]:
npa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

We learned how to generate arrays, now let’s generate multidimensional arrays. These are, as you might guess, arrays with multiple dimensions.

We can create these by reshaping arrays. One of the simplest ways is to just reshape an array with the reshape command. That gives us an x by x array.

In [4]:
npa.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

We can also use the zeros commands.

In [5]:
npa2 = np.zeros((5,5))

In [6]:
npa2

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

To get the size of the array we can use the size method.

In [7]:
npa2.size

25

To get the shape of the array we can use the shape method.

In [8]:
npa2.shape

(5, 5)

to get the number of dimension we use the ndim method.

In [9]:
npa2.ndim

2

We can create as many dimensions as we need to, here's 3 dimensions.

In [10]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
npa2

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [14]:
npa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

Now we can really see the power of vectorization, let’s create two random 2 dimensional arrays.

Now I’m going to set the random seed. This basically makes your random number generation reproducible.

In [23]:
np.random.seed(10)

let’s try some random number generation and then we can perform some matrix comparisons.

In [24]:
npa2 = np.random.random_integers(1,10,25).reshape(5,5)
npa2

array([[10,  5,  1,  2, 10],
       [ 1,  2,  9, 10,  1],
       [ 9,  7,  5,  4,  1],
       [ 5,  7,  9,  2,  9],
       [ 5,  2,  4,  7,  6]])

In [25]:
npa3 = np.random.random_integers(1,10,25).reshape(5,5)
npa3

array([[ 4, 10,  7, 10,  2],
       [10,  5,  3,  7,  8],
       [ 9,  9, 10,  3,  1],
       [ 7,  8,  9,  2,  8],
       [ 2,  5,  1,  9,  6]])

We can do this comparison with greater than or equal to.

In [49]:
npa2 > npa3

array([[ True, False, False, False,  True],
       [False, False,  True,  True, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True],
       [ True, False,  True, False, False]], dtype=bool)

In [29]:
npa2.min()

1

In [31]:
npa2.min(axis=1)

array([1, 1, 1, 2, 2])

In [33]:
npa2.max(axis=0)

array([10,  7,  9, 10, 10])

There are plenty of other functions that numpy as. we can transpose with .T property or transpose method. 

In [34]:
npa2.T

array([[10,  1,  9,  5,  5],
       [ 5,  2,  7,  7,  2],
       [ 1,  9,  5,  9,  4],
       [ 2, 10,  4,  2,  7],
       [10,  1,  1,  9,  6]])

In [36]:
npa2.transpose()

array([[10,  1,  9,  5,  5],
       [ 5,  2,  7,  7,  2],
       [ 1,  9,  5,  9,  4],
       [ 2, 10,  4,  2,  7],
       [10,  1,  1,  9,  6]])

In [38]:
npa2.T == npa2.transpose()

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]], dtype=bool)

We can also multiply this transposition by itself for example. This will be an item by item multiplication

In [39]:
npa2.T * npa2

array([[100,   5,   9,  10,  50],
       [  5,   4,  63,  70,   2],
       [  9,  63,  25,  36,   4],
       [ 10,  70,  36,   4,  63],
       [ 50,   2,   4,  63,  36]])

We can flatten these arrays in several different ways.

we can flatten it, which returns a new array that we can change


In [53]:
np2 = npa2.flatten()
np2

array([10,  5,  1,  2, 10,  1,  2,  9, 10,  1,  9,  7,  5,  4,  1,  5,  7,
        9,  2,  9,  5,  2,  4,  7,  6])